#!/bin/bash

source src/functions;

DATABASE=$(cat src/database_name);

echo "Checando status do postgres..." &&
checkPostgres &&

echo "Destruindo banco de dados..." &&
destroyDatabase $DATABASE

echo "Destruindo banco de dados de teste..." &&
destroyDatabase "${DATABASE}_test";